<?php

/**
 * @file
 * Contains archival links
 */

$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/contributions/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/contributions/ngd_recaptcha-plugin-for-textpattern ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/contributions/small-edit-to-ied_plugin_composer-for-rfc-2045 ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/contributions/securepay-payment-module-for-zencart ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/contributions/newsletter-subscribe ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/contributions/internetsecure-payment-module-for-zencart ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/contributions/gallery-cart',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];

$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/Accessibility',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/blogs',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/Design',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/forums',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/foss',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/humor',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/podcasts',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/quick-reference',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/sources',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/tools',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/Tutorials',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/web-hosting',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/accessibility',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/design',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/resources/tutorials',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];

$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/NotFAQ/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/notfaq/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/NotFAQ/what-is-that-d-link-i-see-on-some-pages ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/NotFAQ/i-have-a-question-for-your-list-how-do-i-submit-it ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/NotFAQ/ive-read-your-pages-and-you-have-called-yourself-notgoddess-elwing-and-sara-jacobson-just-who-are-you-anyway ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/NotFAQ/i-was-looking-for-erigons-webpage-is-this-it ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];

$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/k-s-presentation-on-jupiter ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/learning-html-part-1 ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/regular-expressions-for-common-tasks ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/correct-headers-for-generating-excel-over-ssl ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/xhtml-entity-reference ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/protecting-your-images-on-the-web ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/stop-quirkiness-use-a-proper-doctype ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/articles/roadsigns-for-the-information-superhighway ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/articles/accessibility',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];

$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/its-dead-jim',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/i-conquered-the-world ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/getting-out-of-starvation-mode-and-losing-the-fat ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/meet-my-new-mower',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/support-your-school-libraries ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/fxb-week-1-days-3-4-5-6 ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/fxb-week-1-day-2',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/fxb-week-1-day-1',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/david-tennant-at-amazoncom ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/star-trek-youll-want-to-see-it ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/excuses-by-my-kids',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/david-tennant-new-host-of-masterpiece-contemporary ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/up-all-night-no',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/the-end-of-the-world-as-we-know-it ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/k-in-the-news',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/in-search-of-a-pithy-slogan ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/doctor-who-ideas-sparked-by-the-casting-of-matt-smith-as-the-eleventh-doctor ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/new-new-new-doctor',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/old-shows-new-connections ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/yay-the-kids-are-coming-back ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/new-year-new-new-sara-part-deux ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/dear-readers-take-heed ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/dont-vote-against-write-in-your-candidate ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/please-dont-steal-my-name ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/new-year-new-new-sara ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/its-good-to-have-a-long-term-goal ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/bad-wolf-bad-bad-wolf-bad-naughty-wolf ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/random-speculation-on-doctor-who-series-4 ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/surely-i-cant-be-the-only-one ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/what-is-it-with-me-and-brits ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/what-physical-humor-is-funny ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/little-geniuses',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/and-now-for-something-completely-different ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/sounding-like-a-complete-idiot-is-annoying ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/diet-busters-16',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/vote-your-conscience',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/im-playing-with-the-site-css-be-patient ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/no-flooding-here',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/first-communion-for-1-and-2 ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/temporally-quaquaversal-virtual-nanomachine-programming-in-multiple-topologically-connected-quantum-relativistic-parallel-timespaces-made-easy ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/rant-make-your-php-portable ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/eat-sleep-or-work',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/august-6-2008-doomsday-or-dud ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/phenomenal-music',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/im-a-known-issue',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/ander-as-camille',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/tutorials/learning-html-lesson-1-demo ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/tutorials/learning-html-lesson-2 ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/diet-busters-24',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/diet-busters-37',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/hitler-on-the-torchwood-ii-series-finale ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/i-need-to-post-more',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/chuckle-of-the-day',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/sara-needs',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/that-just-toasts-my-buttons ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/flag-day',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/unearthed-monty-python-footage ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/our-new-home',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/sunshine-and-puppies',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/oh-the-people-you-meet ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/working-through-the-ennui ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/open-letter-to-gm-ford-etc ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/hugh-laurie-go-away',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/trivialities',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/solutions-for-the-firefox-bug-single-quote-or-slash-causes-find-box-to-open ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/its-really-not-funny',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/lyrics-rolling-through-my-head ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/clouds',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/in-loving-memory-kenneth-j-cupps ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/fred',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/all-in-all-a-very-good-day ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/long-lost-and-found',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => ' https://notgoddess.com/archive/journal/spam-and-email-forgery ',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/fiddle-twiddle-boom',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/journal/ander-can-sing',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];

$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/angst/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/goals/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/about/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/review/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/FXB/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/david-tennant/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Humor/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Accessibility/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Design/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/doctor-who/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/family/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Gallery/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/learning-html/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/matt-smith/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Perl/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/PHP/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/politics/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Quick-Reference/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Scripts/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/series/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Site/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/TextPattern/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/Tools/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/ZenCart/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/foss/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
$arbitrary_links[] = [
  'url' => 'https://notgoddess.com/archive/category/humor/',
  'lastmod' => '2019-09-18T05:25:43+00:00',
  'changefreq' => 'never',
  'priority' => '0.1'
];
